### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by cm157** [ddowse/pfSense-pkg-openvpn-multihop#1]
How does the script handle failure in either ingress or egress?

If ingress point fails will it allow leak to egress point from user IP? 

If egress vpn fails will ingress vpn allow iP connections to egress the vpn?

**Comment by ddowse** [comment]
Hello,

the PHP Script does nothing more than it makes sure that the routing is set correct and (re)starting of the tunnels in the order as specified in the configuration. 

Blocking network traffic in any direction is not part of this Plugin/Package as it has to configured with a Ruleset. 

Greetings
